config/routes.rb
require 'resque/server'

Indexer::Application.routes.draw do
  get "policy/tos"
  match "help" => "policy#help"
  get "policy/privacy"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_users do
    mount Resque::Server.new, :at => "/resque" 
  end

  authenticated :user do
    root :to => 'home#search'
  end
  root :to => "home#index"

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations"  }

  resources :accounts do
    resources :account_members
  end
  resources :integrations do
    get 'job_status', :on => :member
    post 'index_now', :on => :member
    resources :authorizations
  end

  get "home/search"

end

app/models/integration.rb
class Integration < ActiveRecord::Base
  resourcify
  has_many :authorizations
  has_many :users, :through => :authorizations
  attr_accessible :auth_type, :name, :url, :description
end

app/controllers/integrations_controller.rb
require 'trello'
require 'rest_client'
require "omniauth"
require 'oauth'
require 'bitbucket_rest_api'
require 'indexer_jobs'

class IntegrationsController < ApplicationController
  load_and_authorize_resource :except => [:index_now, :job_status]
  # GET /integrations
  # GET /integrations.json
  def index
      #@integrations = Integration.all #loaded automatically
      @statuses = {}
      if user_signed_in?
        @integrations.each do |integration|
          user_integration_hash = Rails.cache.read(:user_id => current_user.id, :integration_id => integration.id)
          status = Resque::Plugins::Status::Hash.get(user_integration_hash)
          if status.nil?
            @statuses[integration.id] = ''
          else
            if status.status == "queued"
              @statuses[integration.id] = 'Indexing started'
            else
            @statuses[integration.id] = status.message
            end
          end
        end
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @integrations }
        end
      end
    end

  # GET /integrations/1
  # GET /integrations/1.json
  #def show
  #  @integration = Integration.find(params[:id])
  #
  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @integration }
  #  end
  #end

  # GET /integrations/new
  # GET /integrations/new.json
  #def new
  #  @integration = Integration.new
  #
  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @integration }
  #  end
  #end

  # GET /integrations/1/edit
  #def edit
  #  @integration = Integration.find(params[:id])
  #end

  # POST /integrations
  # POST /integrations.json
  #def create
  #  @integration = Integration.new(params[:integration])
  #
  #  respond_to do |format|
  #    if @integration.save
  #      format.html { redirect_to @integration, notice: 'Integration was successfully created.' }
  #      format.json { render json: @integration, status: :created, location: @integration }
  #    else
  #      format.html { render action: "new" }
  #      format.json { render json: @integration.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # PUT /integrations/1
  # PUT /integrations/1.json
  #def update
  #  @integration = Integration.find(params[:id])
  #
  #  respond_to do |format|
  #    if @integration.update_attributes(params[:integration])
  #      format.html { redirect_to @integration, notice: 'Integration was successfully updated.' }
  #      format.json { head :no_content }
  #    else
  #      format.html { render action: "edit" }
  #      format.json { render json: @integration.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /integrations/1
  # DELETE /integrations/1.json
  #def destroy
  #  @integration = Integration.find(params[:id])
  #  @integration.destroy
  #
  #  respond_to do |format|
  #    format.html { redirect_to integrations_url }
  #    format.json { head :no_content }
  #  end
  #end
  

  


  #Controlller method used for testing integration code
  #def trello
  #  @integration = Integration.find(1)
  #  auth = current_user.authorizations.where(:integration_id => @integration.id).first
  #  Trello::Authorization.const_set :AuthPolicy, OAuthPolicy
  #  OAuthPolicy.consumer_credential = OAuthCredential.new ENV['TRELLO_API_KEY'], ENV['TRELLO_API_SECRET']
  #  OAuthPolicy.token = OAuthCredential.new auth.token, nil
  #
  #  me = Member.find("me")
  #  boards = me.boards(:filter => :all)
  #
  #  all_cards = []
  #
  #  boards.each do |board|
  #    cards = board.cards
  #    cards.each do |card|
  #      all_cards << card.attributes
  #    end
  #  end
  #  render :text => all_cards
  #end

  #Controlller method used for testing integration code
  #def bitbucket
  #  @integration = Integration.find_by_name("Bitbucket")
  #  auth = current_user.authorizations.where(:integration_id => @integration.id).first
  #
  #  bitbucket = BitBucket.new do |config|
  #    config.oauth_token  = auth.token
  #    config.oauth_secret = auth.secret
  #    config.client_id = ENV['BITBUCKET_API_KEY']
  #    config.client_secret = ENV['BITBUCKET_API_SECRET']
  #    config.adapter      = :net_http
  #  end
  #
  #  all_issues = []
  #  bitbucket.repos.list do |repo|
  #     issues = bitbucket.issues.list_repo repo.owner, repo.slug
	 #  issues.each do |i|
  #       issue = bitbucket.issues.get repo.owner, repo.slug, i.local_id
		# all_issues << issue
	 #  end
  #  end
  #  render :json => all_issues
  #end

  def job_status
    if user_signed_in?
    integration_id = params[:id]
    authorize! :retrieve, Integration
    job_id = Rails.cache.read(:user_id => current_user.id, :integration_id => integration_id)
    status = Resque::Plugins::Status::Hash.get(job_id)
    response = {}
    unless status.nil?
      response[:integration_id] = integration_id
      response[:message] = status["message"]
      response[:status] = status["status"]
    end
    render :json =>  response
    else
      render :json => {}
    end
  end
  
      # GET /integrations/1/retrieve
  def index_now #means index now
    if user_signed_in?
      @integration = Integration.find(params[:id])
      authorize! :retrieve, Integration
      auth = current_user.authorizations.where(:integration_id => @integration.id).first
      if @integration.name == "Trello"
        job_id = IndexerJobs::TrelloJob.create({:token => auth.token, :index_id => current_user.id})
        Rails.cache.write({:user_id => current_user.id, :integration_id => @integration.id}, job_id, :time_to_idle => 60.seconds, :timeToLive => 600.seconds)
      elsif @integration.name == "Bitbucket"
        job_id = IndexerJobs::BitbucketJob.create({:token => auth.token, :secret => auth.secret, :index_id => current_user.id})
        Rails.cache.write({:user_id => current_user.id, :integration_id => @integration.id}, job_id, :time_to_idle => 60.seconds, :timeToLive => 600.seconds)
      elsif @integration.name == "Github"
        job_id = IndexerJobs::GithubJob.create({:token => auth.token, :secret => auth.secret, :index_id => current_user.id})
        Rails.cache.write({:user_id => current_user.id, :integration_id => @integration.id}, job_id, :time_to_idle => 60.seconds, :timeToLive => 600.seconds)
      end
      render :json => {:id => @integration.id}
    else
      render :json => {}
    end
  end
  
end

app/helpers/integrations_helper.rb
module IntegrationsHelper
end

app/views/integrations/_form.html.erb
<%= form_for(@integration) do |f| %>
  <% if @integration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@integration.errors.count, "error") %> prohibited this integration from being saved:</h2>

      <ul>
      <% @integration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :auth_type %><br />
    <%= f.text_field :auth_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/integrations/edit.html.erb
<h1>Editing integration</h1>

<%= render 'form' %>

<%= link_to 'Show', @integration %> |
<%= link_to 'Back', integrations_path %>

app/views/integrations/index.html.erb
<h3>Integrations</h3>


<p>

<% if flash[:integration_added]  %>
<script type="text/javascript">
    mixpanel.track("Integration Added");
</script>
<% end %>
<% if flash[:new_user] %>
<script type="text/javascript">
    mixpanel.track("User Signed Up");
    mixpanel.alias("<%= current_user.email %>");
    mixpanel.people.set({
'$email': '<%= current_user.email %>',
'Account Status': 'Trialing',
'$first_name': '<%= current_user.first_name %>',
'$last_name': '<%= current_user.last_name %>',
'$name': '<%= current_user.full_name %>',
'$created': new Date(),
});
</script>
<% end %>
<% if user_signed_in? %>
<% if current_user.integrations.size == 0 %>
    Add your first integration below to get started
<% else %>
    Go to <%= link_to 'search page', '/' %> <i class="icon-hand-right"></i>
<% end %>
<% end %>
</p>
<table>
  <tr>
    <th></th>
    <th/>
    <th/>
    <th/>
  </tr>
  <script src="https://api.trello.com/1/client.js?key=74c0ee95232def21d80dc898878d2382"></script>

  <% @integrations.each do |integration| %>
      <tr>
        <td><h4><%= integration.name %></h4></td>
        <td>
          <% if user_signed_in? %>
	          <% if current_user.integrations.include? integration %>
	             <!-- <%= link_to "Edit", "", :class => "btn"%> -->
	          <% else %>
	            <%= link_to raw("<i class=\"icon-plus\"></i> Add"), user_omniauth_authorize_path(integration.name.downcase.to_sym), :class => "btn", :id => integration.name, 'data-id' => integration.id %>
	          <% end %>
          <% end %>
          </td>
          <td>
          	 <% if user_signed_in? %>
            <% if current_user.integrations.include? integration %>
            <div class="retrieve btn" data-id="<%= integration.id %>">Index Now</div>
            <% end %>
            <% end %>
          </td>
          <td>
          	<% if user_signed_in? %>
            <% if current_user.integrations.include? integration %>
            <div
                <% if @statuses[integration.id] != '' && !@statuses[integration.id].include?('completed') %>
                   class="indexing"
                 <% end %>
                 id="index-status-<%= integration.id %>" data-id="<%= integration.id %>">
           <%= @statuses[integration.id] %>
            </div>
            <% end %>
            <% end %>
          </td>
      </tr>
  <% end %>
</table>
<br/>
<div class="alert">
  <%=t 'integration_feedback' %>
</div>
<br/>

app/views/integrations/new.html.erb
<h1>New integration</h1>

<%= render 'form' %>

<%= link_to 'Back', integrations_path %>

app/views/integrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @integration.name %>
</p>

<p>
  <b>Url:</b>
  <%= @integration.url %>
</p>

<p>
  <b>Auth type:</b>
  <%= @integration.auth_type %>
</p>


<%= link_to 'Edit', edit_integration_path(@integration) %> |
<%= link_to 'Back', integrations_path %>