config/routes.rb
require 'resque/server'

Indexer::Application.routes.draw do
  get "policy/tos"
  match "help" => "policy#help"
  get "policy/privacy"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_users do
    mount Resque::Server.new, :at => "/resque" 
  end

  authenticated :user do
    root :to => 'home#search'
  end
  root :to => "home#index"

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations"  }

  resources :accounts do
    resources :account_members
  end
  resources :integrations do
    get 'job_status', :on => :member
    post 'index_now', :on => :member
    resources :authorizations
  end

  get "home/search"

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  resourcify
  belongs_to :authorization
  belongs_to :integration
  attr_accessible :token, :secret
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  # GET /authorizations
  # GET /authorizations.json
  # def index
    # @authorizations = Authorization.all
# 
    # respond_to do |format|
      # format.html # index.html.erb
      # format.json { render json: @authorizations }
    # end
  # end

  # GET /authorizations/1
  # GET /authorizations/1.json
  # def show
    # @authorization = Authorization.find(params[:id])
# 
    # respond_to do |format|
      # format.html # show.html.erb
      # format.json { render json: @authorization }
    # end
  # end

  # GET /authorizations/new
  # GET /authorizations/new.json
   def create
      authorize! :create, Authorization
      if user_signed_in?
        @integration = Integration.find(params[:integration_id])
        token = params[:token]
        current_user.integrations << @integration
        auth = current_user.authorizations.where(:integration_id => @integration.id).first
        auth.token = token
        auth.save
        #Resque.enqueue(TrelloJob, auth.token)
        job_id = TrelloJob.create({:token => auth.token, :index_id => current_user.id}) # TODO Refactor this
        Rails.cache.write({:user_id => current_user.id, :integration_id => @integration.id}, job_id, :time_to_idle => 60.seconds, :timeToLive => 600.seconds)
        flash[:notice] = "#{@integration.name} Integration Added Successfully"
      end
      render :json => { :redirect_url => '/integrations' }
    end

  # GET /authorizations/1/edit
  #def edit
  #  @authorization = Authorization.find(params[:id])
  #end

  # POST /authorizations
  # POST /authorizations.json
  # def create
    # @authorization = Authorization.new(params[:authorization])
# 
    # respond_to do |format|
      # if @authorization.save
        # format.html { redirect_to @authorization, notice: 'Authorization was successfully created.' }
        # format.json { render json: @authorization, status: :created, location: @authorization }
      # else
        # format.html { render action: "new" }
        # format.json { render json: @authorization.errors, status: :unprocessable_entity }
      # end
    # end
  # end

  # PUT /authorizations/1
  # PUT /authorizations/1.json
  # def update
    # @authorization = Authorization.find(params[:id])
# 
    # respond_to do |format|
      # if @authorization.update_attributes(params[:authorization])
        # format.html { redirect_to @authorization, notice: 'Authorization was successfully updated.' }
        # format.json { head :no_content }
      # else
        # format.html { render action: "edit" }
        # format.json { render json: @authorization.errors, status: :unprocessable_entity }
      # end
    # end
  # end

  # DELETE /authorizations/1
  # DELETE /authorizations/1.json
  def destroy
    @authorization = Authorization.find(params[:id])
    authorize! :delete,  @authorization
    @authorization.destroy

    respond_to do |format|
      format.html { redirect_to integrations_url }
      format.json { head :no_content }
    end
  end
  

  

  
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_form.html.erb
<%= simple_form_for(@authorization) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/authorizations/edit.html.erb
<h1>Editing authorization</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorization %> |
<%= link_to 'Back', authorizations_path %>

app/views/authorizations/index.html.erb
<h1>Listing authorizations</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authorizations.each do |authorization| %>
  <tr>
    <td><%= link_to 'Show', authorization %></td>
    <td><%= link_to 'Edit', edit_authorization_path(authorization) %></td>
    <td><%= link_to 'Destroy', authorization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authorization', new_authorization_path %>

app/views/authorizations/new.html.erb
<h1>New authorization</h1>

<%= render 'form' %>

<%= link_to 'Back', authorizations_path %>

app/views/authorizations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_authorization_path(@authorization) %> |
<%= link_to 'Back', authorizations_path %>