config/routes.rb
require 'resque/server'

Indexer::Application.routes.draw do
  get "policy/tos"
  match "help" => "policy#help"
  get "policy/privacy"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_users do
    mount Resque::Server.new, :at => "/resque" 
  end

  authenticated :user do
    root :to => 'home#search'
  end
  root :to => "home#index"

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations"  }

  resources :accounts do
    resources :account_members
  end
  resources :integrations do
    get 'job_status', :on => :member
    post 'index_now', :on => :member
    resources :authorizations
  end

  get "home/search"

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "AmpleSearch", root_path, :class => 'brand' %>
<ul class="nav pull-right">
  <% if user_signed_in? %>
   <li>
    <%= link_to t('navigation.integrations'), integrations_path %>
   </li>
    <% if current_user.accounts.empty? %>
      <li>
	<%= link_to t('navigation.account'), new_account_path %>
	  </li>
	<% else %>
	<% if current_user.has_role? :owner, current_user.accounts.first %>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to t('navigation.settings'), account_path(current_user.accounts.first) %>
			</li>
			<li>
				<%= link_to t('navigation.team'), account_account_members_path(current_user.accounts.first) %>
			</li>
		</ul>
	</li>
	<% end %>
	<% end %>
    <li>
    <%= link_to(t('navigation.logout'), destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to(t('navigation.login'), new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
  <% else %>
    <li>
    <%= link_to(t('navigation.signup'), new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/_trialing.html.erb
<% if user_signed_in? && current_user.is_trialing %>
<div class="alert">
  <% if current_user.is_trial_expired %>
      <%=t 'trialing.trial_expired' %><strong>
  <% else %>
    <%=t 'trialing.trial_ends' %><%= distance_of_time_in_words(current_user.trial_expiry, Time.zone.now) %>
  <% end %>
  <strong><%= link_to(t('trialing.upgrade_now'), new_account_path) %></strong><%=t 'trialing.paid_account' %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AmpleSearch" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/mW5E9EzxIpDOaU588sq68A.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36824955-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.increment people.append people.track_charge".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||
[]);
<% if Rails.env.production? %>
mixpanel.init("0b8ce25143e34b99b80fbab7d2d473f9");
<% else %>
mixpanel.init("f6b72f308207bcbb536126614ec99b0d");
<% end %>
</script><!-- end Mixpanel -->

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">

           <div class="row content">
              <%= render 'layouts/messages' %>
              <%= yield %>
              <%= render 'layouts/trialing' %>
          </div>
               <br/>         
               <footer>
                 <a href="https://twitter.com/AmpleSearch" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @AmpleSearch</a>
                 <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                 <p>
                 <%= link_to 'Help', help_path %>
                 </p>
               </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>