config/routes.rb
require 'resque/server'

Indexer::Application.routes.draw do
  get "policy/tos"
  match "help" => "policy#help"
  get "policy/privacy"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_users do
    mount Resque::Server.new, :at => "/resque" 
  end

  authenticated :user do
    root :to => 'home#search'
  end
  root :to => "home#index"

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations"  }

  resources :accounts do
    resources :account_members
  end
  resources :integrations do
    get 'job_status', :on => :member
    post 'index_now', :on => :member
    resources :authorizations
  end

  get "home/search"

end

app/models/account.rb
class Account < ActiveRecord::Base
  resourcify
  belongs_to :creator, :class_name => "User"
  has_many :account_members
  has_many :users, :through => :account_members
  attr_accessible :customer_id, :description, :email, :last_4_digits, :stripe_token, :user_count
  attr_accessor :stripe_token
  before_save :update_stripe
  before_destroy :cancel_subscription
  validates :user_count, :numericality => { :only_integer => true, :greater_than => 0 }

  def update_stripe
    #return if email.include?('@example.com') and not Rails.env.production?
    if customer_id.nil?
      if !stripe_token.present?
        raise "Stripe token not present. Can't create account."
      end
      customer = Stripe::Customer.create(
          :email => email,
          :description => description,
          :card => stripe_token,
          :plan => 'per_user',
          :quantity => user_count
      )
    else
      customer = Stripe::Customer.retrieve(customer_id)
      if stripe_token.present?
        customer.card = stripe_token
      end
      customer.email = email
      customer.description = description
      if user_count != customer.subscription.quantity
      customer.update_subscription(:prorate => true, :plan => "per_user", :quantity => user_count)
      end
      customer.save
    end
    self.last_4_digits = customer.active_card.last4
    self.customer_id = customer.id
    self.stripe_token = nil
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "#{e.message}."
    self.stripe_token = nil
    false
  end

  def cancel_subscription
    unless customer_id.nil?
      customer = Stripe::Customer.retrieve(customer_id)
      unless customer.nil? #or customer.deleted # TODO Figure out why undefined method `deleted'
        if customer.subscription.status == 'active'
          customer.cancel_subscription
        end
      end
    end
  rescue Stripe::StripeError => e
    logger.error "Stripe Error: " + e.message
    errors.add :base, "Unable to cancel your subscription. #{e.message}."
    false
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource
  # GET /accounts
  # GET /accounts.json
  #def index
  #  @accounts = Account.all

  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json { render json: @accounts }
  #  end
  #end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    #@account = Account.find(params[:id])
    #authorize! :show, @account
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new
    authorize! :create, Account
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
    authorize! :update, @account
  end

  # GET  /accounts/1/team
  def show_team
    @account = Account.find(params[:id])
    authorize! :view_team, @account
    @members = @account.account_members
    @member = AccountMember.new
  end

   
  # POST /accounts
  # POST /accounts.json
  def create
    #authorize! :create, Account
    #@account = Account.new(params[:account])
    @account.email = current_user.email
    @account.description = current_user.email
    
    respond_to do |format|
      if @account.save
        m = @account.account_members.create( :email => current_user.email)
        m.user = current_user
        current_user.add_role :owner, @account
        if current_user.save && m.save
        flash[:new_account] = true  
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
        else 
          format.html { render action: "new" }
          format.json { render json: @account.errors, status: :unprocessable_entity }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])
    authorize! :update, @account
    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    authorize! :destroy, @account
    @account.destroy
    flash[:notice] = "Account canceled successfully."
    flash[:account_canceled] = true 
    respond_to do |format|
      format.html { redirect_to new_account_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h2>Account</h2>
<div id="stripe_error" class="alert alert-error" style="display:none" ></div>
<h3>Number of Users</h3>
<p>
  <%= @account.user_count %> Users
  <a data-toggle="modal" href="#plan-options" class="btn btn-mini" type="button">Change number of users</a>
</p>

<h3>Card</h3>
<p>
  Using card ending with <%= @account.last_4_digits %>
  <a data-toggle="modal" href="#card-data" class="btn btn-mini" type="button">Change card</a>
</p>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", account_path(@account), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini' %></p>

<div id="plan-options" class="modal" style="display: none;">
  <%= simple_form_for @account, :url => account_path(@account), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
      <div class="modal-header">
        <a class="close" data-dismiss="modal">&#215;</a>
        <h3>Change Number of Users</h3>
      </div>
      <div class="modal-body">
        <%= f.input :user_count %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Change Plan", :class => "btn btn-primary" %>
        <a class="btn" data-dismiss="modal" href="#">Close</a>
      </div>
  <% end %>
</div>

<div id="card-data" class="modal" style="display: none;">
  <%= simple_form_for @account, :url => account_path(@account), :html => {:method => :put, :class => 'form-horizontal card_form' } do |f| %>
      <div class="modal-header">
        <a class="close" data-dismiss="modal">&#215;</a>
        <h3>Change Credit Card</h3>
      </div>
      <div class="modal-body">
        <div class="field">
          <%= label_tag :card_number, "Credit Card Number" %>
          <%= text_field_tag :card_number, nil, name: nil %>
        </div>
        <div class="field">
          <%= label_tag :card_code, "Card Security Code (CVV)" %>
          <%= text_field_tag :card_code, nil, name: nil %>
        </div>
        <div class="field">
          <%= label_tag :card_month, "Card Expiration" %>
          <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"}%>
          <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, {name: nil, id: "card_year"}%>
        </div>
        <%= f.hidden_field :description %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :stripe_token %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Change Credit Card", :class => "btn btn-primary" %>
        <a class="btn" data-dismiss="modal" href="#">Close</a>
      </div>
  <% end %>
</div>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h2>Sign up</h2>
<div id="stripe_error" class="alert alert-error" style="display:none" >
</div>
<%= simple_form_for(@account, :html => {:class => 'card_form form-vertical' }) do |f| %>
    <%= f.error_notification %>
        <div class="field">
          <%= label_tag :card_number, "Credit Card Number" %>
          <%= text_field_tag :card_number, nil, name: nil %>
        </div>
        <div class="field">
          <%= label_tag :card_code, "Card Security Code (CVV)" %>
          <%= text_field_tag :card_code, nil, name: nil %>
        </div>
        <div class="field">
          <%= label_tag :card_month, "Card Expiration" %>
          <%= select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month"}%>
          <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, {name: nil, id: "card_year"}%>
        </div>
    <%= f.input :user_count, :label => 'Number of users ($10 per user per month)' %>
    <%= f.hidden_field :stripe_token %>
    <%= f.button :submit, 'Sign up', :class => 'btn-primary' %>
<% end %>
<% if flash[:account_canceled] %>
<script type="text/javascript">
    mixpanel.track("Account Cancelled")
</script>
<% end %>
<script type="text/javascript">
    mixpanel.track("New Account Page Viewed")
</script>

app/views/accounts/show.html.erb
<h3>Card</h3>
<% if flash[:new_account] %>
<script type="text/javascript">
    mixpanel.track("Account Purchased")
</script>
<% end %>
<p>
  Using card ending with <%= @account.last_4_digits %>
</p>
<p>
  Number of users: <%= @account.user_count %>
</p>

<%= link_to 'Update Account', edit_account_path(@account) %>

app/views/accounts/show_team.html.erb
<p id="notice"><%= notice %></p>
<h1>Team members</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Status</th>
  </tr>
<% @members.each do |team_member| %>
    <tr>
      <td><%= team_member.email %></td>
      <td>
        <% if team_member.user.nil? %>
        Invited
        <% else %>
        Confirmed
        <% end %>
      </td>
    </tr>
<% end %>

</table>


<br />